language: node_js
node_js:
        - "6.9.2"
        - "6.4.0"
        - "6.0.0"
services:
        - mongodb
addons:
        apt:
                sources:
                        - mongodb-3.2-precise
                packages:
                        - mongodb-org-server
